[IV 23-24] Objetivo 0. Actualización del README, idea inicial
danibarranqueroo/TransporteEquitativo pull request #1
Opened 2023-09-27 11:09 UTC by danibarranqueroo

- [x] **¿Se trata de un problema real del que se tenga conocimiento personal?** Si, ya que yo mismo como estudiante en mi día a día muchas veces compro lo que voy a comer al momento y no me paro a pensar en el precio ni en dónde podría ser más barato, haciendo que esté dejando de ahorrar mucho dinero.
- [x] **¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?** Si, para que todo usuario tenga acceso a los recursos necesarios.
- [x] **¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?** Si, la cesta se calcula minimizando el coste ya sea en función de un único supermercado o en función del total de los productos.
- [x] **¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?** Si.
- [x] **¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?** Se requiere únicamente que el usuario introduzca la lista de la compra.

2023-09-27 11:38 UTC, JJ requested changes
En [el guión del objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) dice:

> De la misma forma, aplicaciones que tengan una dependencia externa fuerte (por ejemplo, que recojan datos de un API externo, que pidan una gran cantidad de datos al usuario o que simplemente integren una biblioteca externa para llevar a cabo una operación sobre datos también externos) tampoco van a ser buenos proyectos, porque sus pruebas van a ser complicadas y no van a incluir ningún tipo de modelo. Lo esencial siempre es que la aplicación incluya un valor añadido en forma de lógica de negocio, y que se describa correctamente el problema a solucionar de forma que haga falta tal lógica de negocio para solucionarlo.

Incluso así, "comparar" no parece una lógica de negocio suficientemente sustancial para poder avanzar al objetivo 4.

2023-09-27 11:38 UTC, JJ commented on README.md
> +Aplicación que permita dada una cesta de la compra la minimización del precio de ésta, según lo que desee el usuario se podrá comprar todo en un mismo sitio o cada elemento en el lugar más barato.
¿De dónde vas a obtener los precios? ¿Y los productos posibles que va a haber en la cesta de la compra?

2023-09-27 11:49 UTC, danibarranqueroo commented on README.md
> +Aplicación que permita dada una cesta de la compra la minimización del precio de ésta, según lo que desee el usuario se podrá comprar todo en un mismo sitio o cada elemento en el lugar más barato.
Respecto a la obtención de datos, encontré un excel de 2020 en el que salen productos de distintos supermercados junto con categoría y precios. 
Y respecto a la lógica de negocio sería comparar la lista de productos del usuario con la lista de productos de los supermercados y según lo que prefiera el usuario (comprarlo todo en el mismo sitio o dar vueltas de un supermercado a otro) minimizar el precio de ésta. En clase me dijo que con esos datos y esa lógica de negocio era suficiente, pero si no es así trataré de pensar algún añadido más.

2023-09-27 11:55 UTC, JJ commented on README.md
> +Aplicación que permita dada una cesta de la compra la minimización del precio de ésta, según lo que desee el usuario se podrá comprar todo en un mismo sitio o cada elemento en el lugar más barato.
No sé exactamente lo que te dije, pero primero nada garantiza que lo que me dijiste allí sea exactamente lo que has puesto aquí, y segundo lo que siempre tienes que entender es lo que está escrito.
Es posible que lo que sí te dijera es que *procesar* esa hoja Excel sea el verdadero problema, porque extraer nombres de productos y demás, e identificar cómo se llama un producto en un supermercado y otro puede que tampoco sea trivial. También tendrás que comparar cantidades, por ejemplo, y extraerlas del Excel.

si tienes los productos ordenados por precio, minimizar el precio es simplemente extraer el que tenga un precio menor, y no sería un alógica sustancial. Otra cosa es si tratas de minimizar la cantidad de supermercados a los que hay que ir para comprar la cesta de la compra. Pero en todo caso seguiría siendo una operación relativamente simple (aunque podría tener su interés).

Aclara en todo caso si el problema es extraer los datos (si están semi estructurados, por ejemplo) o dividir una cesta de la compra en un número mínimo de supermercados, o quizás los dos, como HUs diferentes y relacionadas.

2023-09-28 09:42 UTC, danibarranqueroo commented
Listo para revisión, cambio de idea del proyecto.

2023-09-28 10:49 UTC, JJ requested changes
Gracias por haber propuesto un nuevo problema. Igual habría sido más adecuado echar un vistazo al Excel que mencionas y ver si realmente es sencillo extraer nombres de productos y precios, y si el nombre siempre aparece de la misma forma, pero es legítimo que propongas otra cosa.

Sin embargo, hay algún problema con este nuevo envío. El principal es que os hacemos énfasis en que sean problemas con los que estéis familiarizados. Salvo que organices maratones, no creo que sea el caso.

A partir de ahí, hay muchos problemas, pero se pueden resumir en que todo el código que incluyáis debéis escribirlo vosotros, y que no debéis proponer ningún problema que esté ligado a nada físico. En [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) menciona qué tipo de problemas no serían adecuados:

> aplicaciones que tengan una dependencia externa fuerte (por ejemplo, que recojan datos de un API externo, que pidan una gran cantidad de datos al usuario o que simplemente integren una biblioteca externa para llevar a cabo una operación sobre datos también externos) tampoco van a ser buenos proyectos, porque sus pruebas van a ser complicadas y no van a incluir ningún tipo de modelo.

En tu caso, la dependencia externa sería de fotos reales de dorsales reales, y también la biblioteca que necesitarías para reconocimiento de imágenes (porque imagino que escribir desde 0 un algoritmo que lo haga escapa un poco del tiempo que querías dedicarle a la asignatura).

Te aconsejaría que llevaras de nuevo a cabo el proceso de design thinking, bien sobre el problema original que propusiste, bien sobre algo en este área (si es que realmente estás familiarizado con la misma)

2023-09-28 11:55 UTC, danibarranqueroo commented
Buenas JJ, he estado aquí en la cafetería discutiendo con compañeros a ver si sacaba algo para mi objetivo 0 y el resumen es el siguiente: es verdad que para la aplicación de las maratones solo estoy familiarizado en que corro en ellas, para el tema de los supermercados pensándolo bien no se si será posible obtener los datos bien del excel y tal, entonces se me ha ocurrido otro problema pero antes de hacer un nuevo cambio en el readme quería comentártelo por aquí. Mi padre es camionero y trabaja en una cooperativa en mi pueblo (la cooperativa se llama Cotravelma), el problema en esa cooperativa es que la forma de organizar los viajes de los camiones es que cada camionero llegue a la oficina una vez esté de vuelta en Vélez-Málaga y se apunte en una pizarra, luego los de la oficina cuando tienen viajes disponibles miran la pizarra y se lo asignan al que lleve más tiempo parado, esto hace que no sea nada equitativo (por ejemplo a mi padre le ha tocado veces de ir 3 viajes consecutivos a Inglaterra o no ir en 1 año, afectando esto al tiempo que se pasa fuera de casa y al dinero que cobra por viaje), entonces la idea sería hacer esto más equitativo de forma que tenga en cuenta los kms recorridos últimamente, si son 1 o 2 camioneros juntos, la experiencia, el tiempo parado, últimos viajes, si es urgente o no según el destinatario,... haciendo así que sea interesante para que el camionero desde el móvil avise que está en Vélez ya y que también ahí le lleguen las notificaciones de un nuevo viaje (se ahorra ir a la oficina), los de la oficina no tienen que mirar a quien le toca el siguiente viaje ni pensar nada ya que se hace automático y el destinatario puede pagar para que sea urgente y así saber que va a tratarse antes que el resto, perdón por tanto texto pero quiero expresar bien la idea😅

2023-09-28 12:12 UTC, JJ commented
Ponlo en el README expresándolo de la mejor forma posible. Pasa también la lista de comprobación explicando lo que no esté ahí.
Me parece genial que uses la metodología de design thinking (o similar) para esto, te habrás dado cuenta de que así es más sencillo.

2023-09-28 15:29 UTC, JJ commented on README.md
> +La idea sería crear una aplicación que se encargaría de poner en contacto destinatarios, oficina y camioneros, de forma que cada camionero al llegar al parking lo apunta en la aplicación para que ya
Es mejor que no especifiques nada de la solución, sólo lo que ayude a entender que se trata de un problema y qué es lo que quiere la gente qeu se solucione.

2023-09-28 16:27 UTC, merged