[IV-23-24] Objetivo 1
danibarranqueroo/TransporteEquitativo pull request #5
Opened 2023-10-05 07:38 UTC by danibarranqueroo

Sobre los milestones

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Sobre las historias de usuario

* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-10-05 08:23 UTC, pluque01 commented
Me han asignado para revisar tu objetivo, espero ser de ayuda :))

2023-10-05 08:24 UTC, pluque01 commented on docs/historias.md
> +Pepe es camionero en una cooperativa en su pueblo en la que se realizan viajes tanto al extranjero como por españa y le gustaría que la forma en la que se reparten estos viajes entre los distintos ca
¿Qué considera Pepe que es un viaje malo?

2023-10-05 08:24 UTC, pluque01 commented on docs/historias.md
> +La empresa destinataria que encarga la recepción de un determinado producto a través de esta cooperativa de transporte le gustaría que llegara lo más rápido posible y por eso quisiera que tuviera pri
Cuando la empresa destinataria pide tener prioridad respecto a otras, ¿también supondría un aumento de la prima?

2023-10-05 08:24 UTC, pluque01 commented on docs/milestones.md
> +-   Objetivo: Implementar una clase o módulo que dado el resultado del milestone anterior y los camioneros disponibles, proporcione un reparto de viajes justo y equitativo.
En mi opinión deberías especificar qué es un reparto de viajes "justo" y "equitativo"

2023-10-05 10:07 UTC, PabloBarTo requested changes
Buenas me ha tocado ser tu revisor, intentaré ayudarte en todo lo que sea posible.

2023-10-05 10:07 UTC, PabloBarTo commented on docs/historias.md
> +# Historias de Usuarios
En general yo añadiría un poco más de contexto y especificaría más en algunos aspectos, como por ejemplo como ha dicho @pluque01, que se considera un viaje "malo" o que se debe cumplir para que una empresa pueda tener prioridad sobre otra.

2023-10-05 10:41 UTC, danibarranqueroo commented
Gracias por vuestra ayuda, trato de cambiar lo que me habéis comentado y ya os aviso cuando esté listo de nuevo :raised_hands: @pluque01 @PabloBarTo

2023-10-05 11:06 UTC, danibarranqueroo commented
Ya he modificado un poco los ficheros que me habéis dicho, además al mirar el tema de los milestones y el reparto de viajes, he pensado que realmente la prioridad del destinatario se tiene que tener en cuenta para la asignación de los viajes a los camioneros por lo que he cambiado el orden de esto.

2023-10-06 06:42 UTC, pluque01 commented
Okey, ahora le echo un vistazo

2023-10-06 07:06 UTC, pluque01 reviewed
He hecho algunos comentarios, sin embargo lo que me parece más importante es que tu lógica de negocio del milestone 1 debe ser lo suficientemente compleja para el objetivo 4. En el punto actual es algo trivial, por lo que te recomiendo eliminar o modificar ese milestone.

2023-10-06 07:06 UTC, pluque01 commented on docs/milestones.md
> +    -   El sistema debe ser preciso y eficiente.
No creo que esto aporte información relevante

2023-10-06 07:06 UTC, pluque01 commented on docs/milestones.md
> +    -   El sistema debe ser fácil de usar para los camioneros y los oficinistas.
Tampoco es información relevante

2023-10-07 10:31 UTC, danibarranqueroo commented
He seguido tus consejos @pluque01 y he quitado información irrelevante y además he pensado en juntar los dos primero milestones porque como dices el que tenía como M1 era demasiado trivial, cuando puedas le echas un vistazo y gracias por la ayuda!

2023-10-08 10:43 UTC, pluque01 commented
Yo lo veo mucho mejor; solicita revisión al profesor. ¡Ánimo!

2023-10-08 10:43 UTC, pluque01 approved these changes

2023-10-09 06:48 UTC, danibarranqueroo commented
De acuerdo, @JJ uno de mis revisores ya lo ve listo para su revisión.

2023-10-09 07:55 UTC, JJ commented
Prefiero que haya dos, y si es posible, tres... De hecho, @PabloBarTo no lo ha aprobado y tampoco has reaccionado al comentario que te ha hecho.

2023-10-09 08:07 UTC, danibarranqueroo commented on docs/historias.md
> +# Historias de Usuarios
Buenas @PabloBarTo te contesto por aquí por si no viste que te mencioné hace 4 días haciendo los cambios que me propusiste

2023-10-09 08:14 UTC, PabloBarTo commented on docs/historias.md
> +# Historias de Usuarios
Perdona, no lo había visto. Te lo reviso ya.

2023-10-09 08:19 UTC, PabloBarTo requested changes

2023-10-09 08:19 UTC, PabloBarTo commented on docs/historias.md
> +Paco es uno de los oficinistas encargados de gestionar los viajes y de asignarlo a los camioneros, está harto de escuchar quejas por parte de destinatarios y de camioneros por lo que le gustaría disp
Aquí en vez de "asignarlo" yo pondría "asignarlos".

2023-10-09 09:23 UTC, danibarranqueroo commented on docs/historias.md
> +Paco es uno de los oficinistas encargados de gestionar los viajes y de asignarlo a los camioneros, está harto de escuchar quejas por parte de destinatarios y de camioneros por lo que le gustaría disp
Gracias! No me había dado cuenta, ya está cambiado.:smiley:

2023-10-09 09:46 UTC, PabloBarTo approved these changes
Yo creo que ya está listo para que te lo revise el profesor. Mucha suerte!

2023-10-10 06:30 UTC, danibarranqueroo commented
Perfecto! @JJ ninguno de los otros revisores ha dicho nada desde que se les asignó, como los dos que si me han ayudado ya han aprobado los cambios te vuelvo a mencionar.

2023-10-10 06:50 UTC, JJ requested changes
Gracias por el trabajo realizado, pero creo que queda por hacer, tanto en la especificación de las HUs, como en la de los milestones.
También recuerda resolver los comentarios que están efectivamente resueltos, con el commit en el que se ha hecho, si es que no se ha cambiado la línea sobre la que se ha hecho el comentario.

2023-10-10 06:50 UTC, JJ commented on docs/historias.md
> +Paco es uno de los oficinistas encargados de gestionar los viajes y de asignarlos a los camioneros, está harto de escuchar quejas por parte de destinatarios y de camioneros por lo que le gustaría dis
¿La diferencia entre este y el anterior es que se tienen en cuenta más criterios?

2023-10-10 06:50 UTC, JJ commented on docs/milestones.md
> +-   Objetivo: Calcular las distintas variables a tener en cuenta de cada camionero en lo que va de mes, así como implementar la opción de dar prioridad a los envíos por parte de los destinatarios.
Trata de reflejar de forma más precisa la lógica de negocio qeu se va a implementar. "Calcular las variables" no lo refleja.

2023-10-10 06:50 UTC, JJ commented on docs/milestones.md
> +    -   El sistema debe tener en cuenta los factores especificados en las historias de usuario HU1 y HU2.
Y esto viene a decir que las dos usan la misma lógica de negocio, y por tanto serían la misma HU.

2023-10-10 07:06 UTC, danibarranqueroo commented on docs/historias.md
> +La empresa destinataria que encarga la recepción de un determinado producto a través de esta cooperativa de transporte le gustaría que llegara lo más rápido posible y por eso quisiera que tuviera pri
Resuelto en el commit `63d0e2e1b8907af8d5beb73eebb311546ecdb4da`

2023-10-10 07:07 UTC, danibarranqueroo commented on docs/historias.md
> +# Historias de Usuarios
Resuelto en el commit `63d0e2e1b8907af8d5beb73eebb311546ecdb4da`

2023-10-10 07:08 UTC, danibarranqueroo commented on docs/milestones.md
> +-   Objetivo: Implementar clase o módulo que proporcione a los destinatarios la opción de dar prioridad a sus envíos.
Resuelto en el commit `d4731b187ed927560316fe5dba5a1dc2f90fffdf`

2023-10-10 07:08 UTC, danibarranqueroo commented on docs/milestones.md
> +    -   El sistema debe ser preciso y eficiente.
Resuelto en el commit `d4731b187ed927560316fe5dba5a1dc2f90fffdf`

2023-10-10 07:09 UTC, danibarranqueroo commented on docs/milestones.md
> +    -   El sistema debe ser fácil de usar para los camioneros y los oficinistas.
Resuelto en el commit `d4731b187ed927560316fe5dba5a1dc2f90fffdf`

2023-10-10 07:09 UTC, danibarranqueroo commented on docs/historias.md
> +Paco es uno de los oficinistas encargados de gestionar los viajes y de asignarlo a los camioneros, está harto de escuchar quejas por parte de destinatarios y de camioneros por lo que le gustaría disp
Resuelto en el commit `6d7d3eb149e9ad37fc57ffec951fd66ff1d781ce`

2023-10-10 07:12 UTC, danibarranqueroo commented on docs/historias.md
> +Paco es uno de los oficinistas encargados de gestionar los viajes y de asignarlos a los camioneros, está harto de escuchar quejas por parte de destinatarios y de camioneros por lo que le gustaría dis
En principio, la diferencia es que son dos personas distintas, con distintos problemas, pero que van a usar el mismo programa, pero los criterios que se usan son los mismos.

2023-10-10 07:13 UTC, danibarranqueroo commented on docs/milestones.md
> +-   Objetivo: Calcular las distintas variables a tener en cuenta de cada camionero en lo que va de mes, así como implementar la opción de dar prioridad a los envíos por parte de los destinatarios.
De acuerdo, ahora trato de modificarlo.

2023-10-10 07:14 UTC, JJ commented on docs/historias.md
> +Paco es uno de los oficinistas encargados de gestionar los viajes y de asignarlos a los camioneros, está harto de escuchar quejas por parte de destinatarios y de camioneros por lo que le gustaría dis
¿Cuál es el problema? ¿Que esté harto? Si lo que quiere es repartir los viajes de forma equitativa, no es *su* problema.

2023-10-10 07:16 UTC, danibarranqueroo commented on docs/milestones.md
> +## [M2] Implementar el sistema de reparto de viajes equitativo
He tratado de poner dos milestones como para dividir el trabajo en dos, pero realmente la lógica de negocio se podría resumir todo en un único milestone ya que el cálculo de variables del que hablo al principio es trivial, lo más complicado puede ser los kilómetros recorridos pero sabiendo los últimos destinos es solo distancia entre dos lugares, por tanto, si lo ve adecuado podría tratar de juntarlo todo en un único milestone.

2023-10-10 07:16 UTC, JJ commented on docs/milestones.md
> +    -   El sistema debe tener en cuenta los factores especificados en las historias de usuario HU1 y HU2.
No preguntes lo que tienes que hacer. Yo sólo te voy a decir qué es lo que observo o qué has pasado por alto. A partir de ahí haz lo que consideres conveniente, y yo te volveré a evaluar.
Si dos usuarios distintos tienen el mismo problema, que por tanto se resuelve con la misma lógica de negocio, ¿siguen siendo usuarios distintos?

2023-10-10 07:17 UTC, JJ commented on docs/milestones.md
> +## [M2] Implementar el sistema de reparto de viajes equitativo
Yo veré adecuado (o no) cuando lo que pongas en el PR refleje que has alcanzado los objetivos de aprendizaje. Así que una vez más haz lo que hayas entendido, y refléjalo en el PR.

2023-10-10 07:43 UTC, danibarranqueroo commented
He tratado de modificar un poco todo teniendo en cuenta sus sugerencias. :raised_hands:

2023-10-10 08:06 UTC, JJ approved these changes
:+1: Gracias por resolverlo tan rápidamente.

2023-10-10 08:14 UTC, merged